- name: copy file
  hosts: deploys
  gather_facts: yes
  become: yes
  become_user: administrator

  tasks:
    - name: copy file
      ansible.windows.win_copy:
       src: ~/.ssh/ansible_karlson/*.ps1
       dest: c:\temp\
      register: script_return
    - debug:
        msg: "{{ script_return }}"
  
