---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:

  - add_host:
      hostname: "{{ target_hosts }}"
      group: dynamic

- hosts: dynamic
  become: false
  gather_facts: false
  become_user: administrator
  
  become_method: runas

  tasks:
  - name: copy file NNIT_Windows_Server_Audit
    ansible.windows.win_copy:
      src: ~/.ssh/ansible_karlson/NNIT_Windows_Server_Audit.ps1
      dest: c:\temp\
      register: script_return
   # - debug:
   #   msg: "{{ script_return }}"
    
  #- name: Create audit report
  #  ansible.windows.win_powershell:
  #    path: C:\temp\NNIT_Windows_Server_Audit.ps1
  #    remote_src: true
      
  - name: List audit report
    command: type c:\temp\*report.log
    register: command_output

  - name: Print to console
    debug:
      msg: "{{command_output.stdout}}"

