---
- name: Create VMware VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "vsphere.karlson.dk"
    vcenter_username: "karlson\administrator"
    #vcenter_password: "YourPassword"
    datacenter_name: "Lyngby"
    cluster_name: "Karlson"
    datastore_name: "Datastore10_1"
    vm_name: "ansible-testvm"
    #vm_template: "ubuntu-template"
    vm_network: "VM Network"

  tasks:
    - name: Deploy VM with full spec
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false

        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        datastore: "{{ datastore_name }}"

        hardware:
          memory_mb: 8192
          num_cpus: 4
          num_cpu_cores_per_socket: 2

        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "192.168.10.50"
            netmask: "255.255.255.0"
            gateway: "192.168.10.1"
            dns_servers:
              - "192.168.10.10"

        disks:
          - size_gb: 40
            type: thin
            datastore: "{{ datastore_name }}"
          - size_gb: 100
            type: thin
            datastore: "{{ datastore_name }}"

        customization:
          hostname: "{{ vm_name }}"
          domain: "example.com"

        state: poweredon
      register: vm_output
