---
- name: Create VMware VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "vsphere.karlson.dk"
    vcenter_username: "karlson\administrator"
    #vcenter_password: "YourPassword"
    datacenter_name: "Lyngby"
    cluster_name: "Karlson"
    datastore_name: "Datastore10_1"
    vm_name: "ansible-testvm"
    vm_template: "ubuntu-template"
    vm_network: "VM Network"

  tasks:
    - name: Create VM from template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false

        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        datastore: "{{ datastore_name }}"

        networksnetworks: - name: "{{ vm_network }}" 
	state: poweredon 
	register: deploy
