---
- hosts: deploys
  gather_facts: false
  become: false
  tasks:
  become_user: administrator
  become_method: runas
  - name: copy file NNIT_Windows_Server_Audit
    ansible.windows.win_copy:
      src: ~/.ssh/ansible_karlson/NNIT_Windows_Server_Audit.ps1
      dest: c:\temp\
      register: script_return
   # - debug:
   #   msg: "{{ script_return }}"
    
  - name: Create audit report
    ansible.windows.win_powershell:
      path: C:\temp\NNIT_Windows_Server_Audit.ps1
      remote_src: true
 
