- name: create audit report
  hosts: deploys
  gather_facts: yes
  become: yes
  become_user: administrator

  tasks:
  
  - name: Create audit report
    ansible.windows.win_powershell:
      path: C:\temp\NNIT_Windows_Server_Audit.ps1
      remote_src: true
