---
- name: Create Proxmox VM from ISO
  hosts: localhost
  gather_facts: false

  vars:
    api_host: "pve.karlson.dk"
    api_user: "root@pam"
    api_token_secret: "e3863f22-2d05-4203-a364-c1698fd3c0d2"
    api_token_id: "ansible"
    api_password: "I was a monkey14"
    node: "pve"

    vm_id: 120
    vm_name: "iso-vm-test"
    iso_storage: "local"
    iso_image: "iso/ubuntu-22.04-live-server-amd64.iso"

  tasks:

  - name: Create empty VM
    community.general.proxmox_kvm:
      api_host: "{{ api_host }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_password: "{{ api_password }}"
      ostype: "auto" 
      node: "{{ node }}"
      vmid: "{{ vm_id }}"
      hostname: "testing"
      ide: 
        ide2: "local:iso/ubuntu-22.04-live-server-amd64.iso,media=cdrom"
      memory: 4096
      cores: 2
      state: present

  
