---
- name: Create Proxmox VM from ISO
  hosts: localhost
  gather_facts: false

  vars:
    api_host: "pve.karlson.dk"
    api_user: "root@pam"
    api_token_secret: "e3863f22-2d05-4203-a364-c1698fd3c0d2"
    api_token_id: "ansible"
    node: "pve"
    sockets: 2 
    cores: 2
    cputype: "x86-64-v2-AES"
    vm_id: 120
    vm_name: "iso-vm-test"
    iso_storage: "local"
    iso_image: "iso/en-us_windows_server_2025_updated_sep_2025_x64_dvd_6d1ad20d_unattend.iso"

  tasks:

  - name: Create empty VM
    community.general.proxmox_kvm:
      api_host: "{{ api_host }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      ostype: "win11" 
      node: "{{ node }}"
      vmid: "{{ vm_id }}"
      name: "{{ vm_name }}"
      sockets: "{{ sockets }}" 
      cores: "{{ cores }}" 
      cpu: "{{ cputype }}"
      ide: 
        ide2: "{{ iso_storage }}:{{ iso_image }},media=cdrom"
      memory: 4096
      scsihw: "pvscsi" 
      scsi: 
        scsi0: "local-lvm:90"
      state: present

  - name: Start VM to begin ISO installation
    community.general.proxmox_kvm:
      api_host: "{{ api_host }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      node: "{{ node }}"
      vmid: "{{ vm_id }}"
      state: started
