---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:

  - add_host:
      hostname: "{{ target_hosts }}"
      group: dynamic

- hosts: dynamic
  become: false
  gather_facts: false
  become_user: administrator
  become_method: runas
  
  tasks: 

  - name: Read file contents on Windows
    win_shell: |
    Get-Content -Path "C:\Temp\ptest1.karlson.dk-2026-02-03-Audit-Report.log" -Raw
    register: file_output

  - name: Show file contents
    debug:
      msg: "{{ file_output.stdout }}"
