---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:

  - add_host:
      hostname: "{{ target_hosts }}"
      group: dynamic

- hosts: dynamic
  become: false
  gather_facts: false
  become_user: administrator
  become_method: runas
  
  tasks: 
  - name: List audit report
    command: cat "ansible.cfg"
    register: command_output
  - name: Print to console
    debug:
      msg: "{{command_output.stdout}}"

