- name: Restart service
  hosts: windows
  gather_facts: yes
  become: yes

  tasks:
    - name: restart service
      ansible.windows.win_powershell:
        script: 
          get-service | where {$_.displayname -eq "Windows Time"} | restart-service
      register: script_return
    - debug:
        msg: "{{ script_return }}"
