---
- hosts: windows
  gather_facts: true
  become: true
  

  tasks:
  
  
  - name: restart service
      ansible.windows.win_powershell:
      script:
        get-service | where {$_.name -eq "Windows Time"} | restart-service
      register: script_return
    - debug:
        msg: "{{ script_return }}"
