#- name: Restart service
---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:

  - add_host:
      hostname: "{{ target_hosts }}"
      group: dynamic

- hosts: dynamic
  become: true
  gather_facts: true
  #become_user: karlson\ansible
  
  #become_method: runas
  
  tasks:
    - name: restart service
      ansible.windows.win_powershell:
        script: 
          get-service | where {$_.displayname -eq "Windows Time"} | restart-service
      register: script_return
    - debug:
        msg: "{{ script_return }}"
