#- name: Restart service
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:

  - add_host:
      hostname: "{{ target_hosts }}"
      group: dynamic

- hosts: dynamic
  become: true
  gather_facts: true
  
  tasks:
    - name: restart service
      ansible.windows.win_powershell:
        script: 
          get-service | where {$_.displayname -eq "Windows Time"} | restart-service
      register: script_return
    - debug:
        msg: "{{ script_return }}"
